FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
	build-essential gcc libpq-dev \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN pip install poetry \
	&& poetry config virtualenvs.create false \
	&& poetry install --no-root --no-interaction --no-ansi

COPY swingtraderai swingtraderai
COPY alembic alembic
COPY alembic.ini .
COPY celery_app.py .

CMD ["celery", "-A", "celery_app.celery", "worker", "--loglevel=info"]